# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: J:/work/HY/Xilinx/A704/V1.0/PRJ/XDC/debug.xdc

# XDC: J:/work/HY/Xilinx/A704/V1.0/PRJ/XDC/io_test.xdc

# XDC: J:/work/HY/Xilinx/A704/V1.0/PRJ/XDC/pin.xdc

# XDC: J:/work/HY/Xilinx/A704/V1.0/PRJ/XDC/timing.xdc

# IP: J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/ddr_ctrl/ddr3/ddr3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr3 || ORIG_REF_NAME==ddr3} -quiet] -quiet

# IP: J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/clk_ctrl/IP/ddr_clk/ddr_clk.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr_clk || ORIG_REF_NAME==ddr_clk} -quiet] -quiet

# IP: J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/clk_ctrl/IP/sys_clk/sys_clk.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_clk || ORIG_REF_NAME==sys_clk} -quiet] -quiet
