# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "J:/work/HY/Xilinx/A704/V1.0/PRJ/Project/top.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir J:/work/HY/Xilinx/A704/V1.0/PRJ/Project/top.cache/wt [current_project]
set_property parent.project_path J:/work/HY/Xilinx/A704/V1.0/PRJ/Project/top.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo j:/work/HY/Xilinx/A704/V1.0/PRJ/Project/top.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/uart_ctrl/ascii_code.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/clk_ctrl/clk_ctrl.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/uart_ctrl/device_temp_ascii_dis.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/ddr_ctrl/example_top.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/io_test/io_test.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/led_ctrl/led_ctrl.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/ddr_ctrl/traffic_gen/mig_7series_v4_2_afifo.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/ddr_ctrl/traffic_gen/mig_7series_v4_2_cmd_gen.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/ddr_ctrl/traffic_gen/mig_7series_v4_2_cmd_prbs_gen.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/ddr_ctrl/traffic_gen/mig_7series_v4_2_data_prbs_gen.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/ddr_ctrl/traffic_gen/mig_7series_v4_2_init_mem_pattern_ctr.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/ddr_ctrl/traffic_gen/mig_7series_v4_2_memc_flow_vcontrol.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/ddr_ctrl/traffic_gen/mig_7series_v4_2_memc_traffic_gen.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/ddr_ctrl/traffic_gen/mig_7series_v4_2_rd_data_gen.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/ddr_ctrl/traffic_gen/mig_7series_v4_2_read_data_path.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/ddr_ctrl/traffic_gen/mig_7series_v4_2_read_posted_fifo.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/ddr_ctrl/traffic_gen/mig_7series_v4_2_s7ven_data_gen.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/ddr_ctrl/traffic_gen/mig_7series_v4_2_tg_prbs_gen.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/ddr_ctrl/traffic_gen/mig_7series_v4_2_tg_status.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/ddr_ctrl/traffic_gen/mig_7series_v4_2_traffic_gen_top.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/ddr_ctrl/traffic_gen/mig_7series_v4_2_vio_init_pattern_bram.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/ddr_ctrl/traffic_gen/mig_7series_v4_2_wr_data_gen.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/ddr_ctrl/traffic_gen/mig_7series_v4_2_write_data_path.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/uart_ctrl/reset_bridge.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/rst_ctrl/rst_ctrl.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/uart_ctrl/uart_tx/uart_baud_gen.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/uart_ctrl/uart_state.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/uart_ctrl/uart_top.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/uart_ctrl/uart_tx/uart_tx.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/uart_ctrl/uart_tx/uart_tx_ctl.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/xadc_temp/xadc_temp.v
  J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/top.v
}
read_ip -quiet J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/ddr_ctrl/ddr3/ddr3.xci
set_property used_in_implementation false [get_files -all j:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/ddr_ctrl/ddr3/ddr3/user_design/constraints/ddr3.xdc]
set_property used_in_implementation false [get_files -all j:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/ddr_ctrl/ddr3/ddr3/user_design/constraints/ddr3_ooc.xdc]

read_ip -quiet J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/clk_ctrl/IP/ddr_clk/ddr_clk.xci
set_property used_in_implementation false [get_files -all j:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/clk_ctrl/IP/ddr_clk/ddr_clk_board.xdc]
set_property used_in_implementation false [get_files -all j:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/clk_ctrl/IP/ddr_clk/ddr_clk.xdc]
set_property used_in_implementation false [get_files -all j:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/clk_ctrl/IP/ddr_clk/ddr_clk_late.xdc]
set_property used_in_implementation false [get_files -all j:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/clk_ctrl/IP/ddr_clk/ddr_clk_ooc.xdc]

read_ip -quiet J:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/clk_ctrl/IP/sys_clk/sys_clk.xci
set_property used_in_implementation false [get_files -all j:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/clk_ctrl/IP/sys_clk/sys_clk_board.xdc]
set_property used_in_implementation false [get_files -all j:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/clk_ctrl/IP/sys_clk/sys_clk.xdc]
set_property used_in_implementation false [get_files -all j:/work/HY/Xilinx/A704/V1.0/PRJ/RTL/clk_ctrl/IP/sys_clk/sys_clk_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc J:/work/HY/Xilinx/A704/V1.0/PRJ/XDC/debug.xdc
set_property used_in_implementation false [get_files J:/work/HY/Xilinx/A704/V1.0/PRJ/XDC/debug.xdc]

read_xdc J:/work/HY/Xilinx/A704/V1.0/PRJ/XDC/io_test.xdc
set_property used_in_implementation false [get_files J:/work/HY/Xilinx/A704/V1.0/PRJ/XDC/io_test.xdc]

read_xdc J:/work/HY/Xilinx/A704/V1.0/PRJ/XDC/pin.xdc
set_property used_in_implementation false [get_files J:/work/HY/Xilinx/A704/V1.0/PRJ/XDC/pin.xdc]

read_xdc J:/work/HY/Xilinx/A704/V1.0/PRJ/XDC/timing.xdc
set_property used_in_implementation false [get_files J:/work/HY/Xilinx/A704/V1.0/PRJ/XDC/timing.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7a35tfgg484-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
